version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo ======================Pre build ==================
      - pwd
      - ls -al
      - ls -al ./src/main/resources/
      - aws s3 cp s3://servletdemobucket/jdbc.properties ./src/main/resources/jdbc.properties
      - ls -al ./src/main/resources/
  build:
    commands:
      - mvn package

  post_build:
    commands:

      - mv target/servletsDemo-1.0.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*